[lib]
path = "src/lib.rs"
name = "lucy"

[package]
name = "lucy"
version = "0.1.0"
edition = "2021"

[dependencies]
url = { version = "2" }
rand = { version = "0.8.0" }

[dev-dependencies]
fakes-gen = "0.2.6"
